title: "Tom Titcombe / An ML Journey"
theme: jekyll-theme-cayman
name: "Tom Titcombe"
description: "A collection of thoughts on privacy, machine learning and tech."

cayman-blog:
  date_format: "%-d %b, %Y"

author: "Tom Titcombe"
BASE_PATH: /
