title: "Tom Titcombe / An ML Journey"
theme: jekyll-theme-cayman
name: "Tom Titcombe"
description: "A collection of thoughts on privacy, machine learning, data viz and data science."

cayman-blog:
  date_format: "%-d %b, %Y"

author: "ttitcombe"
